//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDXWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantFundRaised
    {
        public int ID { get; set; }
        public string IssuerCode { get; set; }
        public string WarrantType { get; set; }
        public Nullable<decimal> AdditionalAdjustedShares { get; set; }
        public Nullable<System.DateTime> ListingDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> FundRaised { get; set; }
    
    }
}